# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Grafana Agent add-on
version: '1.2.0'
slug: grafana-agent
description: Grafana Agent add-on
url: 'https://github.com/jdcmarques/hassio-grafana-agent/tree/main/grafana-agent'
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: 'Hello world...'
schema:
  message: 'str?'
image: 'ghcr.io/jdcmarques/hassio-grafana-agent/{arch}'
